notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.net#concerto"
    use_notice: true
    skip_join: true

language: php

php:
  - 5.4
  - 5.5
  - 5.6

install: ./scripts/travis-install.sh

script: php vendor/bin/phpunit --configuration ./phpunit.xml --coverage-text